name: Redate commits
on: workflow_dispatch

jobs:
  redate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Redate commits
        run: |
          git config user.email "vlad1m1rvallt88@gmail.com"
          git config user.name "SamojlovVladimir"
          
          COMMITS=$(git log d8e1f85f6f40f8a427980dfcb05e8b4c241a423a..HEAD --format="%H" | tail -n +4)
          
          git rebase d8e1f85f6f40f8a427980dfcb05e8b4c241a423a \
            --exec 'GIT_AUTHOR_DATE="2025-06-20T12:00:00" GIT_COMMITTER_DATE="2025-06-20T12:00:00" git commit --amend --no-edit'

      - name: Force push
        run: git push --force
